In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("assets/penguins_cleaned.csv") #อ่านไฟล์ csv จาก assets
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181,3750,male
1,Adelie,Torgersen,39.5,17.4,186,3800,female
2,Adelie,Torgersen,40.3,18.0,195,3250,female
3,Adelie,Torgersen,36.7,19.3,193,3450,female
4,Adelie,Torgersen,39.3,20.6,190,3650,male
...,...,...,...,...,...,...,...
328,Chinstrap,Dream,55.8,19.8,207,4000,male
329,Chinstrap,Dream,43.5,18.1,202,3400,female
330,Chinstrap,Dream,49.6,18.2,193,3775,male
331,Chinstrap,Dream,50.8,19.0,210,4100,male
332,Chinstrap,Dream,50.2,18.7,198,3775,female

In [3]:
df.info()
#print(X.dtypes) #เช็ค type แต่ละ column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    object
 1   island             333 non-null    object
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    int64
 5   body_mass_g        333 non-null    int64
 6   sex                333 non-null    object
dtypes: float64(2), int64(2), object(3)
memory usage: 18.3+ KB

In [4]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      333.000000     333.000000         333.000000   333.000000
mean        43.992793      17.164865         200.966967  4207.057057
std          5.468668       1.969235          14.015765   805.215802
min         32.100000      13.100000         172.000000  2700.000000
25%         39.500000      15.600000         190.000000  3550.000000
50%         44.500000      17.300000         197.000000  4050.000000
75%         48.600000      18.700000         213.000000  4775.000000
max         59.600000      21.500000         231.000000  6300.000000

In [5]:
df_2 = df.drop('species',axis = 1)
df_2

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Torgersen,39.1,18.7,181,3750,male
1,Torgersen,39.5,17.4,186,3800,female
2,Torgersen,40.3,18.0,195,3250,female
3,Torgersen,36.7,19.3,193,3450,female
4,Torgersen,39.3,20.6,190,3650,male
...,...,...,...,...,...,...
328,Dream,55.8,19.8,207,4000,male
329,Dream,43.5,18.1,202,3400,female
330,Dream,49.6,18.2,193,3775,male
331,Dream,50.8,19.0,210,4100,male
332,Dream,50.2,18.7,198,3775,female

In [6]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181,3750,male
1,Adelie,Torgersen,39.5,17.4,186,3800,female
2,Adelie,Torgersen,40.3,18.0,195,3250,female
3,Adelie,Torgersen,36.7,19.3,193,3450,female
4,Adelie,Torgersen,39.3,20.6,190,3650,male
...,...,...,...,...,...,...,...
328,Chinstrap,Dream,55.8,19.8,207,4000,male
329,Chinstrap,Dream,43.5,18.1,202,3400,female
330,Chinstrap,Dream,49.6,18.2,193,3775,male
331,Chinstrap,Dream,50.8,19.0,210,4100,male
332,Chinstrap,Dream,50.2,18.7,198,3775,female

In [7]:
X = df.drop('species' , axis = 1)
X

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Torgersen,39.1,18.7,181,3750,male
1,Torgersen,39.5,17.4,186,3800,female
2,Torgersen,40.3,18.0,195,3250,female
3,Torgersen,36.7,19.3,193,3450,female
4,Torgersen,39.3,20.6,190,3650,male
...,...,...,...,...,...,...
328,Dream,55.8,19.8,207,4000,male
329,Dream,43.5,18.1,202,3400,female
330,Dream,49.6,18.2,193,3775,male
331,Dream,50.8,19.0,210,4100,male
332,Dream,50.2,18.7,198,3775,female

In [8]:
y = df.species #เลือก column species มาขึ้น dataframe y
y

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...
328    Chinstrap
329    Chinstrap
330    Chinstrap
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: object